//! Scenario scripts (D10): commands with their expected events, checked against any book.
//!
//! A script is the text command format (D6) plus:
//! - `> ...` lines: the expected output of the line above
//! - `book`: print the book as a ladder, asks above bids, highest price first:
//!   `ask <price> <qty> (<orders>)`, then `bid ...`, or `empty`
//! - `#` comments and blank lines, kept as they are
//!
//! `transcript` drops the `>` lines, re-runs the script and writes fresh ones, so a
//! scenario passes exactly when it equals its own transcript.

use std::fmt::Write;

use crate::book::OrderBook;
use crate::command::{Command, Event};
use crate::types::Side;

/// Run one script line against `book`, appending `> ` output lines to `out`.
/// Also used by the REPL. Comments and blank lines produce nothing.
pub fn run_line<B: OrderBook>(book: &mut B, line: &str, out: &mut String) -> Result<(), String> {
    let line = line.trim();
    if line.is_empty() || line.starts_with('#') {
        return Ok(());
    }
    if line == "book" {
        for row in render_book(book) {
            writeln!(out, "> {row}").unwrap();
        }
        return Ok(());
    }
    let cmd: Command = line.parse().map_err(|e| format!("{e}"))?;
    let mut events: Vec<Event> = Vec::new();
    book.apply(&cmd, &mut events);
    for event in &events {
        writeln!(out, "> {event}").unwrap();
    }
    book.check_invariants()
        .map_err(|e| format!("invariant broken after `{line}`: {e}"))
}

/// The script with every `>` line regenerated by running it.
pub fn transcript<B: OrderBook>(book: &mut B, script: &str) -> Result<String, String> {
    let mut out = String::new();
    for (n, line) in script.lines().enumerate() {
        if line.trim_start().starts_with('>') {
            continue;
        }
        out.push_str(line);
        out.push('\n');
        run_line(book, line, &mut out).map_err(|e| format!("line {}: {e}", n + 1))?;
    }
    Ok(out)
}

/// The whole book as a ladder: asks from highest to lowest, then bids from highest to lowest,
/// so the spread sits in the middle.
pub fn render_book<B: OrderBook>(book: &B) -> Vec<String> {
    let mut rows: Vec<String> = book
        .depth(Side::Sell, usize::MAX)
        .iter()
        .rev()
        .map(|l| format!("ask {} {} ({})", l.price, l.qty, l.orders))
        .collect();
    rows.extend(
        book.depth(Side::Buy, usize::MAX)
            .iter()
            .map(|l| format!("bid {} {} ({})", l.price, l.qty, l.orders)),
    );
    if rows.is_empty() {
        rows.push("empty".to_string());
    }
    rows
}

/// Where two texts first differ, for a readable test failure.
pub fn first_difference(expected: &str, actual: &str) -> Option<String> {
    let mut exp = expected.lines();
    let mut act = actual.lines();
    for n in 1.. {
        match (exp.next(), act.next()) {
            (None, None) => return None,
            (e, a) if e == a => continue,
            (e, a) => {
                return Some(format!(
                    "line {n}:\n  expected: {}\n  actual:   {}",
                    e.unwrap_or("<end of file>"),
                    a.unwrap_or("<end of output>")
                ))
            }
        }
    }
    unreachable!()
}
